### ISSUE TITLE
Add complete set of tests to all sources

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/dbt_omop_rxn_silver#1]
We need all sources (which represent the bronze layer ingested from on-prem) to have a comprehensive set of tests. Let's document what these tests need to be on this issue and start picking these off in batches.

~Currently all sources are listed in `./models/sources.yml`. We may want to split this into multiple files at a later stage.~

Sources are documented in multiple yaml files under `./models/omop_sources`.

**Comment by quindavies** [comment]
OMOP specific tests complete
Date test discussion continued on https://github.com/lsc-sde/dbt_omop_rxn_silver/issues/11
