### ISSUE TITLE
`source_to_concept_map` is missing in dbt_omop.prod

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/dbt_omop_rxn_silver#2]
- [ ] We need this copied over from prd_omop - it is on the Adatis contracts but ingestion fails as it is not in the on-prem data.
- [ ] We also need a way to generate this table automatically.

**Comment by quindavies** [comment]
Now present in on-prem data.
Have created a new issue in our other repository to add a new model and generate this automatically.
